server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://49.234.66.129:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    #- classpath*:top/**/mapper/*.xml
