server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://49.234.66.129:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: 49.234.66.129
    database: 0 # Redis数据库索引（默认为0）
    port: 6379
    password: 12345678
    jedis:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8  # 连接池中的最大空闲连接
        min-idle: 0  # 连接池中的最小空闲连接
    timeout: 3000ms  # 连接超时时间（毫秒）

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    #- classpath*:top/**/mapper/*.xml

# 自定义Redis Key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120 # 验证码超期时间
