server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://49.234.66.129:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678

#mybatis:
#  mapper-locations:
#    - classpath: mapper/*.xml
#    - classpath*: top/**/mapper/*.xml
